/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Dynamic: typeof import('@solidjs/web').Dynamic
  const Errored: typeof import('solid-js').Errored
  const For: typeof import('solid-js').For
  const Loading: typeof import('solid-js').Loading
  const Match: typeof import('solid-js').Match
  const Portal: typeof import('@solidjs/web').Portal
  const Repeat: typeof import('solid-js').Repeat
  const Reveal: typeof import('solid-js').Reveal
  const Show: typeof import('solid-js').Show
  const Switch: typeof import('solid-js').Switch
  const children: typeof import('solid-js').children
  const createContext: typeof import('solid-js').createContext
  const createEffect: typeof import('solid-js').createEffect
  const createMemo: typeof import('solid-js').createMemo
  const createRenderEffect: typeof import('solid-js').createRenderEffect
  const createRoot: typeof import('solid-js').createRoot
  const createSignal: typeof import('solid-js').createSignal
  const createStore: typeof import('solid-js').createStore
  const createUniqueId: typeof import('solid-js').createUniqueId
  const fluentOn: typeof import('@/primitives/fluentOn').fluentOn
  const flush: typeof import('solid-js').flush
  const hydrate: typeof import('@solidjs/web').hydrate
  const isServer: typeof import('@solidjs/web').isServer
  const lazy: typeof import('solid-js').lazy
  const mapArray: typeof import('solid-js').mapArray
  const merge: typeof import('solid-js').merge
  const omit: typeof import('solid-js').omit
  const onCleanup: typeof import('solid-js').onCleanup
  const onSettled: typeof import('solid-js').onSettled
  const reconcile: typeof import('solid-js').reconcile
  const render: typeof import('@solidjs/web').render
  const snapshot: typeof import('solid-js').snapshot
  const tryAsync: typeof import('@/utils/tryAsync').tryAsync
  const trySync: typeof import('@/utils/tryAsync').trySync
  const untrack: typeof import('solid-js').untrack
  const useBeforeLeave: typeof import('@solidjs/router').useBeforeLeave
  const useContext: typeof import('solid-js').useContext
  const useIsRouting: typeof import('@solidjs/router').useIsRouting
  const useLocation: typeof import('@solidjs/router').useLocation
  const useMatch: typeof import('@solidjs/router').useMatch
  const useNavigate: typeof import('@solidjs/router').useNavigate
  const useParams: typeof import('@solidjs/router').useParams
  const useSearchParams: typeof import('@solidjs/router').useSearchParams
}
